spring.application.name: spring-ai-basic
spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: 'gpt-4o'
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
